config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :invoices

  resources :quotes
  resources :clients

  resources :devis
  get '/modify_client' => 'application#modify_client'
  get '/visu_pdf/quote_visu' => 'visu_pdf#quote_visu'
  put '/visu_pdf/quote_send' => 'visu_pdf#quote_send'
  put '/visu_pdf/sub_invoice_send' => 'visu_pdf#sub_invoice_send'
  get '/quotes/:id/invoice' => 'quotes#invoice'
  put '/quotes/:id/status' => 'quotes#status'
  get '/new_invoice' => 'invoices#new_invoice'
  put '/sub_inv_create/:id' => 'sub_invoice#create'
  put 'sub_invoice_mark_paid/:id' => 'sub_invoice#mark_paid'
  put 'sub_invoice_mark_unpaid/:id' => 'sub_invoice#mark_unpaid'
  delete '/sub_invoice/:id' => 'sub_invoice#delete'
  get '/visu_pdf/sub_invoice_visu' => 'visu_pdf#sub_invoice_visu'
  get '/report' => 'visu_pdf#report'
  

  

  root 'visu_pdf#report'

end

app/models/quote.rb
class Quote < ActiveRecord::Base

serialize :list
belongs_to :client, :class_name => "Client"
		
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  before_action :authenticate_user!, :set_quote, only: [:show, :edit, :update, :destroy, :index]
  layout 'application'
  # GET /quotes
  # GET /quotes.json

  def index
    @order=params[:order].to_i
    if @order==1
      @quotes=Quote.order(title: :asc).all
    elsif @order==2
      @quotes=Quote.order(title: :desc).all
    elsif @order==3
      @quotes=Quote.joins("left join clients on quotes.client_id = clients.id").order("clients.last_name ASC")
    elsif @order==4
      @quotes=Quote.joins("left join clients on quotes.client_id = clients.id").order("clients.last_name DESC")
    elsif @order==5
      @quotes=Quote.order(total: :asc).all
    elsif @order==6
      @quotes=Quote.order(total: :desc).all
    elsif @order==7
      @quotes=Quote.order(created_at: :desc).all
    elsif @order==8
      @quotes=Quote.order(created_at: :asc).all
    elsif @order==9
      @quotes=Quote.order(status: :desc).all
    elsif @order==10
      @quotes=Quote.order(status: :asc).all

    else
      @quotes = Quote.all
    end
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show

   @quote = Quote.find(params[:id])
   # @clients = Client
   # @alpha=('a'..'z').to_a + ('0'..'9').to_a
   @client= Client.find_by_id(@quote.client_id)
   if @quote.list==nil
    @lmax=0
    else
   @lmax=@quote.list.length
   end
   if @quote.total==nil
    @total=0
    else
   @total=@quote.total
   end
   @tax_rate=@quote.tax_rate
   if @tax_rate==nil
     @tax_rate=0
   end
   @hash=Hash.new
   i=0
     while i<@lmax do
      @hash.merge!({i => @quote.list[i]})
      i=i+1
     end
     if @lmax==0
      @hash={0=>["", "", "", ""]}
    end
  end

  # GET /quotes/new
  def new
    @clients = Client
    @alpha=('a'..'z').to_a + ('0'..'9').to_a
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
    @quote = Quote.find(params[:id])
    UserMailer.send_quote(@quote).deliver
    respond_to do |format|
      format.html { redirect_to quotes_url }
      format.json { head :no_content }
    end
  end

  def status
  @quote = Quote.find(params[:id])
  @quote.update({:status=>params['q_param']['status'].to_d, :endtime=>Time.now})
    if @quote.status == 2
      invoice_create(@quote)
    end
  end

  def invoice
    q = Quote.find(params[:id])
    q.update({:status=>2, :endtime=>Time.now})
    invoice_create(q)
    respond_to do |format|
      format.html { redirect_to @invoice }
      format.json { head :no_content }
    end
  end

  def invoice_create(quote)
    q=quote
    c = Client.find(q.client_id)
    @invoice=c.invoices.create(:title=>q.title,:total=>q.total,:list=>q.list,:tax_rate=>q.tax_rate,:comment=>q.comment, :quote_id=>q.id)
  end



  # POST /quotes
  # POST /quotes.json
def create
  @client=Client.find_by_id(params['q_param']['client'])
  title=params['q_param']['title']
  comment=params['q_param']['comment']
  list = [["","","1",""]]
  quote_p={:title=>title,:comment=>comment, :status=>1, :list=>list}
  @quote = @client.quotes.create(quote_p)
  render json:  {:quote_id=>@quote.id}

  # respond_to do |format|
  #   if @quote.save
  #     format.html { redirect_to index, notice: 'Quote was successfully created.' }
  #     # format.json { render action: 'show', status: :created, location: @quote }
  #   else
  #     format.html { render action: 'new' }
  #     # format.json { render json: @quote.errors, status: :unprocessable_entity }
  #   end
  # end
end




  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
  @quote = Quote.find(params[:id])
  title=params['q_param']['title']
  total=params['q_param']['total']
  tax_rate=params['q_param']['tax_rate']
  l=params['q_param']['list']
  comment=params['q_param']['comment']
  list=Array.new
    l.keys.each do |j|
      list << [l[j][0],l[j][1],l[j][2],l[j][3]]
    end
   quote_p={:title=>title,:total=>total,:list=>list,:tax_rate=>tax_rate,:comment=>comment}
   @quote.update(quote_p)

  # respond_to do |format|
  #   if @quote.update(quote_p)
  #       format.html {}
        format.json { head :no_content }
  #   else
  #       format.html {}
  #       format.json { render json: @quote.errors, status: :unprocessable_entity }
  #   end
  # end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote = Quote.find(params[:id])
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      
    end
    # def send_quote(quote)
    #   @quote=quote
    #   if params['q_param']['q_send']=="true"
    #     UserMailer.send_quote(@quote).deliver
    #   end


    # end


    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params[:quote]
    end

end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/index.html.erb
  <div class='row'>
    <div class='col-sm-12'>
      <div class='page-header'>
        <h1 class='pull-left'>
          <i class='icon-inbox'></i>
          <span>Devis</span>
        </h1>
      </div>

<a class="btn btn-success btn-block btn-lg" type="button" href="/quotes/new">Nouveau devis</a>
          <p></p>
        </div>
        </div>
 

 <div class='row'>
  <div class='col-sm-12'>
    <div class='box bordered-box orange-border' style='margin-bottom:0;'>
      <div class='box-content box-no-padding'>
        <div class='responsive-table'>
          <div class='scrollable-area'>
            <table class='data-table-column-filter table table-bordered table-striped' style='margin-bottom:0;'>
        <thead>
            <tr>
                <th width="25%">Titre du devis</th>
                <th width="20%">Nom du client</th>
                <th width="15%">Montant</th>
                <th width="15%">Date de création</th>
                <th width="15%">Statut</th>
                <th width="10%">Actions</th>
            </tr>
        </thead>
 
        <tfoot>
            <tr>
                <th>Titre du devis</th>
                <th>Nom du client</th>
                <th>Montant</th>
                <th>Date de création</th>
                <th>Statut</th>
                <th>Actions</th>
            </tr>
        </tfoot>
 
        <tbody>
            <% @quotes.each do |quote| %>
                <tr>
                  <td>
                          <%= link_to(quote) do %>
                            #<%= quote.id %>  <%= quote.title %> 

                          <% end %>
                </td>
                <td>
                  <% @client=Client.find_by_id(quote.client_id) %>

                  <%= link_to(clients_path) do %>
                    <%=@client.first_name.capitalize%> <%=@client.last_name.capitalize %>       
                  <% end %>
                </td>
                <td>
                        <% 
                        @tax_rate=quote.tax_rate
                        if @tax_rate==nil
                          @tax_rate=0
                        end 
                        %>
                        <%= quote.total.to_d*(1+@tax_rate.to_d) if quote.total!=nil %> € TTC
                </td>
                <td>
                          <span><%= distance_of_time_in_words(Time.now, quote.created_at) %></span>
                          <i class='icon-time'></i>
                </td>
                <td>
                  <a data-toggle="modal" href="#modal-status_<%=quote.id%>"><span class="label 
                      <%="label-important" if quote.status==0%><%="label-warning" if quote.status==1%><%="label-success" if quote.status==2%>"><%="Devis refusé" if quote.status==0%><%="Devis en cours" if quote.status==1%><%="Devis accepté" if quote.status==2%></span></a>
                </td>
                <td>
                  <h4>
                    <a href="" class='has-tooltip' data-placement="top" data-original-title="Visualiser"onclick="window.open('/visu_pdf/quote_visu.<%= quote.id %>','_blank');"><i class="icon-search"></i></a>
                      &nbsp;
                    <a class='has-tooltip' data-placement="top" data-original-title="Facturer" data-toggle="modal" href="/quotes/<%= quote.id %>/invoice"><i class="icon-money"></i></a>
                      &nbsp; 
                    <%= link_to '<i class="icon-trash"></i>'.html_safe, quote, method: :delete, data: { confirm: 'Etes vous sûr de vouloir supprimer ce devis?', placement: "top", original_title: "Supprimer" },class: 'has-tooltip' %>
                    </h4>
                     <div class='modal fade' id='modal-status_<%=quote.id%>' tabindex='1'>
                      <div class='modal-dialog'>
                        <div class='modal-content'>
                          <div class='modal-header'>
                            <button aria-hidden='true' class='close' data-dismiss='modal' type='button'>×</button>
                            <h4 class='modal-title' id='myModalLabel'>Modifier le statut du devis #<%=quote.id%> - <%=quote.title%></h4>
                          </div>
                          <div class='modal-body'>
                            <form class="form" style="margin-bottom: 0;" method="post" action="#" accept-charset="UTF-8"><input name="authenticity_token" type="hidden" />
                              <div class='form-group'>
                                <label for='status'>Statut</label>
                                <select class="form-control input-sm" data-rule-required="true" id="status_select_<%=quote.id%>" name="validation_select">
                                    <option <%= "selected" if quote.status==1 %>>Devis en cours</option>
                                    <option <%= "selected" if quote.status==2 %>>Devis accepté</option>
                                    <option <%= "selected" if quote.status==0 %>>Devis refusé</option>
                                </select>
                              </div>
                            </form>
                          </div>
                          <div class='modal-footer'>
                            <button class='btn btn-default' data-dismiss='modal' type='button'>Fermer sans modifier le statut</button>
                            <button class='btn btn-success' data-dismiss='modal' type='button' onclick="quoteStatus(<%= quote.id %>);">Modifier le statut</button>
                          </div>
                        </div>
                      </div>
                    </div>  
                  </td>
                </tr>
              <% end %>
        </tbody>
    </table>
  </div>  
  </div>
  </div>
    </div>  
  </div>
  </div>


  <script type="text/javascript">
  $( document ).ready(function() {
    $("#nav_quote").toggleClass('active');
});

function quoteStatus(id) {
var status_select="status_select_"+id;
var status="";
    if (document.getElementById(status_select)==null){
      status=1;
    }
    else{
      if (document.getElementById(status_select).value=="Devis en cours") {
        status=1;
      };
      if (document.getElementById(status_select).value=="Devis accepté") {
        status=2;
      };
      if (document.getElementById(status_select).value=="Devis refusé") {
        status=0;
      };
    }
var url_send= "/quotes/"+id+"/status";  
var request=$.ajax({
url: url_send,
type: "PUT",
beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
data: {q_param: {
         status: status
       }}
});

request.done(finishStatus(id));
}

function finishStatus(id){
  var url_show;
  url_show="/quotes";
 window.location.replace(url_show);
}


      $("#daterange2").daterangepicker({
        format: "MM/DD/YYYY"
      }, function(start, end) {
        return $("#daterange2").parent().find("input").first().val(start.format("MMMM D, YYYY") + " - " + end.format("MMMM D, YYYY"));
      });
      
  </script>


<br>

app/views/quotes/new.html.erb
<div id="notice"><%= notice %></div> 


<div id='orders'>
<div class='row'>
  <div class='col-sm-12'>
    <div class='page-header'>
      <h1 class='pull-left'>
        <i class='icon-inbox'></i>
        <span>Nouveau devis </span>
      </h1>
    </div>
	  <div class='col-sm-12'>
      <h3>1. Choisir le client</h3>
    <div class='row' id='detail'>
      <div class='col-sm-12'>
        <div class='box'>
          <div class='box-content'>
	          <div class='row' >
	          	<div class='col-sm-6'>
			          <div class='clearfix' id='slider'>
				          <div class='slider-content'>
				            <ul class='list-unstyled'>
				              <% @alpha.each do |car| %>
				                <% if @clients.where(ln_fl: car)!=[] %>
				                  <li id="<%=car%>">
				                    <a class='title' name="<%=car%>"><%=car.upcase%></a>
				                    <ul class='list-unstyled'>
				                      <% @clients.where(ln_fl: car).sort_by{ |m| m.last_name.downcase}.each do |client| %>
				                        <li>
				                          <a href='#' onclick="clientShow(<%= client.id %>);return false;"> <%= client.last_name %> <%= client.first_name %></a>
				                        </li>
				                      <% end %>
				                    </ul>
				                  </li>
				                <% end %>
				              <% end %>
				            </ul>
				          </div>
			          </div>
			        </div>
						  <div class='col-sm-6'>
				        <div class='pull-right'>
                  <%= link_to 'Nouveau Client', new_client_path %>
				        </div>
				        <div class='lead'>
				          <i class='icon-user contrast'></i>
				          Contact client
				        </div>
				        <address>
				          <strong><div id='full_name'></div></strong>
                  <div id='company'></div>
				          <a href='mailto:#' id='email'></a>
				        </address>
				        <div class='lead'>
				          <i class='icon-envelope contrast'></i>
				          Addresse client
				        </div>
				        <address>
				          <strong><div id='full_name'></div></strong>
				          <div id='address'></div>
				          <div id='city'></div>
				          <div id='phone'></div>
				        </address>
						      </div>
						    </div>
              </div>
            </div>

       <h3>2. Informations générales sur le devis</h3>

      <div class="box-content box-no-padding">
        <div class='box'>
          <div class='box-content'>
            <div class='form-group'>
              <form class="form" style="margin-bottom: 0;" method="post" action="#" accept-charset="UTF-8"><input name="authenticity_token" type="hidden" /><div class='form-group'>
              <label for='q_title'>Titre du devis</label>
              <input class='form-control' id='q_title' placeholder='Titre du devis' type='text' value=''>
            </div>
            <div class='form-group'>
              <label for='q_comment'>Commentaire sur le devis</label>
              <textarea class='form-control' id='q_comment' placeholder="Commentaire pour le devis - le texte s'affichera sur le devis envoyé au client" rows='7'></textarea>
            </div>
          </div>
        </div>
      </div>

            
          </div>
            <hr class='hr-normal'>
            <div>
              <span>
                <div class='text-right'>
<!--                   <a class='btn btn-success' target="_blank" onclick="quoteVisu(); return false;">Visualiser</a> -->
                  <a class='btn btn-success' onclick="quoteNext(); return false;">Suivant</a>
                </div>
              </span>                  
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<script>
  $( document ).ready(function() {
    $("#nav_quote").toggleClass('active');
});

var idclient;
var data=0;
var request;

function clientShow(id){
	idclient=id;
  $( "#full_name" ).empty();
  $( "#email" ).empty();
  $("#email").attr("href", "#");
  $( "#address" ).empty();
  $( "#city" ).empty();
  $( "#phone" ).empty();
  $("#editClient").attr("href", "#");
  $( "#editClient" ).empty();
  $("#deleteClient").attr("href", "#");
  $( "#deleteClient" ).empty();
 $( "#company" ).empty();



  var url_client_up="/clients/"+id+"/edit";
  var url_up="/clients/"+id+".json";
  var url_del="/clients/"+id;

  var request=$.get( url_up, function( data ) {
  $( "#full_name" ).append( "" + capitaliseFirstLetter(data.client.last_name) + " " + capitaliseFirstLetter(data.client.first_name) );
 $( "#company" ).append( "" + capitaliseFirstLetter(data.client.company) );

  $( "#email" ).append( "" + data.client.email );
  $( "#email" ).attr("href", "mailto:"+data.client.email );
  $( "#address" ).append( "" + data.client.address );
  $( "#city" ).append( "" +data.client.postal_code + " " + capitaliseFirstLetter(data.client.city) );
  $( "#phone" ).append( "" + data.client.phone );
  $("#editClient").attr("href", url_client_up);
  $( "#editClient" ).append( "Editer client" );
  $("#deleteClient").attr("href", url_del);
  $( "#deleteClient" ).append( "Supprimer client" );

}, "json" );

}


function capitaliseFirstLetter(string)
{
  if (string==null){
    return ""
  }
  else{
    return string.charAt(0).toUpperCase() + string.slice(1);
  }
}

function quoteCreate(num_function){
	if (idclient==undefined || idclient==null) {
            alert('Merci de choisir un client');
            return false;
  }
  event.preventDefault();
  var url_up="/quotes"
  var title=document.getElementById("q_title").value;
  var comment=document.getElementById("q_comment").value;

        request=$.ajax({
        url: url_up,
        type: "POST",
        beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
        data: {q_param: {
                 title: title, 
                 comment: comment,
                 client: idclient,
               }},
        success: function(data, textStatus, jqXHR) {
                  // if (num_function==0){request.done(goBack());}
                  // if (num_function==1){request.done(goShow(data.quote_id));}
                  // return false;
                  request.done(goShow(data.quote_id));
                  // if (num_function==0){request.done(goBack());}
                },
        dataType: "json"
        });
    return true;
}


// function goBack() {
//  window.location.replace("/quotes");
// }

function goShow(quote_id) {
var url_show;
url_show="/quotes/"+quote_id;
// var url_visu="/visu_pdf/quote_visu."+quote_id
// window.location.replace(url_show);
 window.location.replace(url_show);
return true;
}
// function setData(data){
//   data=data;
//   var url_visu="/visu_pdf/quote_visu."+data;
//   // window.location.replace(url_show);
//   window.open(url_visu, '_blank');
//   return true;
// }

function quoteNext(){
quoteCreate(0);
}

// function quoteVisu(){
// quoteCreate(1);
// }
</script>