config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :invoices

  resources :quotes
  resources :clients

  resources :devis
  get '/modify_client' => 'application#modify_client'
  get '/visu_pdf/quote_visu' => 'visu_pdf#quote_visu'
  put '/visu_pdf/quote_send' => 'visu_pdf#quote_send'
  put '/visu_pdf/sub_invoice_send' => 'visu_pdf#sub_invoice_send'
  get '/quotes/:id/invoice' => 'quotes#invoice'
  put '/quotes/:id/status' => 'quotes#status'
  get '/new_invoice' => 'invoices#new_invoice'
  put '/sub_inv_create/:id' => 'sub_invoice#create'
  put 'sub_invoice_mark_paid/:id' => 'sub_invoice#mark_paid'
  put 'sub_invoice_mark_unpaid/:id' => 'sub_invoice#mark_unpaid'
  delete '/sub_invoice/:id' => 'sub_invoice#delete'
  get '/visu_pdf/sub_invoice_visu' => 'visu_pdf#sub_invoice_visu'
  get '/report' => 'visu_pdf#report'
  

  

  root 'visu_pdf#report'

end

app/models/client.rb
class Client < ActiveRecord::Base
has_many :quotes, :class_name => "Quote", :foreign_key => "client_id", dependent: :destroy
has_many :invoices, dependent: :destroy
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!, :set_client, only: [:show, :edit, :update, :destroy]
  layout 'application'
  # GET /clients
  # GET /clients.json
  def index
    @clients = Client
    @alpha=('a'..'z').to_a + ('0'..'9').to_a;
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @quotes=Array.new
    @client.quotes.each do |q|
      arr=[q.title,q.total,q.id,distance_of_time_in_words(Time.now, q.created_at)]
      @quotes<<arr
    end
    hash={:client=>@client,:quotes=>@quotes}
    render json:  hash
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)
    respond_to do |format|
      if @client.save
        format.html { redirect_to clients_url, notice: 'Client was successfully created.' }
        format.json { render action: 'show', status: :created, location: @client }
      else
        format.html { render action: 'new' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to clients_url, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params      
      params[:client].merge!({'ln_fl' => params[:client][:last_name][0].downcase})
      params[:client].permit(:last_name, :first_name, :email, :address, :postal_code, :phone, :city,:ln_fl,:company)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
      <p>
  <%=f.label :email %>
  <br/>
  <%=f.text_field :email %>
  </p>
  <p>
  <%=f.label :first_name %>
  <br/>
  <%=f.text_field :first_name %>
  </p>
  <p>
  <%=f.label :last_name %>
  <br/>
  <%=f.text_field :last_name %>
  </p>
  <p>
  <%=f.label "Société" %>
  <br/>
  <%=f.text_field :company %>
  </p>
  <%=f.label "Numéro de TVA" %>
  <br/>
  <%=f.text_field :TVA_num %>
  </p>
  <p>
  <%=f.label :address %>
  <br/>
  <%=f.text_field :address %>
  </p>
    <p>
  <%=f.label :city %>
  <br/>
  <%=f.text_field :city %>
  </p>
      <p>
  <%=f.label :postal_code %>
  <br/>
  <%=f.text_field :postal_code %>
  </p>
    <p>
  <%=f.label :phone %>
  <br/>
  <%=f.text_field :phone %>
  </p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
      

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

<script type="text/javascript">
  $( document ).ready(function() {
    $("#nav_client").toggleClass('active');
});
</script>

app/views/clients/index.html.erb
<div class='row'>
  <div class='col-sm-12'>
    <div class='page-header'>
      <h1 class='pull-left'>
        <i class='icon-envelope'></i>
        <span>Carnet d'adresse</span>
      </h1>
    </div>
  </div>
</div>
<div class='row'>
  <div class='col-sm-12'>
    <div class='col-sm-6'>
        <h1>
      <a class="has-tooltip" data-original-title="Créer un nouveau Client" data-placement="right" href="/clients/new"><i class=" icon-plus contrast"></i></a>
      </h1>
    </div> 
    <div class='col-sm-6'>
       <div class="pull-left">
         <a href='#' id='editClient'></a>
       </div>
       <div class="pull-right">
         <a data-confirm="Are you sure?" data-method="delete" href='#' id='deleteClient' rel="nofollow"></a>
       </div>
    </div>


  </div>
</div>
<div class='row'>
  <div class='col-sm-6'>
    <div class='box'>
      <div class='box-content box-no-padding'>
        <div class='clearfix' id='slider'>
          <div class='slider-content'>
            <ul class='list-unstyled'>
              <% @alpha.each do |car| %>
                <% if @clients.where(ln_fl: car)!=[] %>
                  <li id="<%=car%>">
                    <a class='title' name="<%=car%>"><%=car.upcase%></a>
                    <ul class='list-unstyled'>
                      <% @clients.where(ln_fl: car).sort_by{ |m| m.last_name.downcase}.each do |client| %>
                        <li>
                          <a href='#' onclick="clientShow(<%= client.id %>); return false;"> <%= client.last_name %> <%= client.first_name %></a>
                        </li>
                      <% end %>
                    </ul>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class='col-sm-6'>
    <div id='showJSON'></div>
      <div class='col-sm-6'>
        <div class='lead'>
          <i class='icon-user contrast'></i>
          Contact client
        </div>
        <address>
          <strong><div id='full_name'></div></strong>
          <div id='company'></div>
          <a href='mailto:#' id='email'></a>
        </address>
      </div>
      <div class='col-sm-6'>
        <div class='lead'>
          <i class='icon-envelope contrast'></i>
          Adresse client
        </div>
        <address>
          <strong><div id='full_name'></div></strong>
          <div id='address'></div>
          <div id='city'></div>
          <div id='phone'></div>
        </address>
      </div>
    </div>
    <div class='col-sm-6'>
      <div class='clearfix'></div>
      <hr class='hr-normal'>
      <div id="quote_list"></div>
    </div>
  </div>
</div>


<script type="text/javascript">
$('#slider').sliderNav()
</script>

<script type="text/javascript">
  $( document ).ready(function() {
    $("#nav_client").attr('class', 'active');
});


function clientShow(id){

  $( "#full_name" ).empty();
  $( "#email" ).empty();
  $("#email").attr("href", "#");
  $( "#address" ).empty();
  $( "#city" ).empty(); 
   $( "#company" ).empty();
  $( "#phone" ).empty();
  $("#editClient").attr("href", "#");
  $( "#editClient" ).empty();
  $("#deleteClient").attr("href", "#");
  $( "#deleteClient" ).empty();
  $("#quote_list").empty();

  var url_client_up="/clients/"+id+"/edit";
  var url_up="/clients/"+id+".json";
  var url_del="/clients/"+id;

  var request=$.get( url_up, function( data ) {

  $( "#full_name" ).append( "" + capitaliseFirstLetter(data.client.last_name) + " " + capitaliseFirstLetter(data.client.first_name) );
  $( "#company" ).append( "" + capitaliseFirstLetter(data.client.company) );
  $( "#email" ).append( "" + data.client.email );
  $( "#email" ).attr("href", "mailto:"+data.client.email );
  $( "#address" ).append( "" + data.client.address );
  $( "#city" ).append( "" + data.client.postal_code + " " + capitaliseFirstLetter(data.client.city) );
  $( "#phone" ).append( "" + data.client.phone );
  $("#editClient").attr("href", url_client_up);
  $( "#editClient" ).append( '<h4><i class="icon-edit"></i></h4>' );
  $("#deleteClient").attr("href", url_del);
  $( "#deleteClient" ).append( "Supprimer client" );
  data.quotes.forEach(function(a) {
      
      var title=a[0];
      var total=a[1];
      var id=a[2];
      var date=a[3];
      $("#quote_list").append('<div class="col-sm-12"><div class="pull-left"><p><a href="/quotes/'+id+'"><strong>  #'+id+' '+title+' </strong></a><p><i class="icon-time"></i><span> '+date+'</span></p></p></div><div class="text-right pull-right"><h5 class="contrast price">'+total+' €</h5></div></div></div><div class="clearfix"></div><hr class="hr-normal">'
        );
      

  });

}, "json" );

}


function capitaliseFirstLetter(string)
{
  if (string==null){
    return ""
  }
  else{
    return string.charAt(0).toUpperCase() + string.slice(1);
  }
}


</script>

app/views/clients/new.html.erb
<h1>Nouveau client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>
<script type="text/javascript">
  $( document ).ready(function() {
    $("#nav_client").attr('class', 'active');
});
</script>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>